/**
 * CONSTELLATION — MASTER INFORMATION MODEL
 * 
 * 16 Universal Entity & Artifact Categories
 * + 7-Tier Epistemological Separation
 * + Crime Genres & Taxonomies
 */

// ── 7-TIER EPISTEMOLOGICAL SEPARATION ──────────────────────────────
export const EPISTEMIC_TIERS = [
  {
    tier: 1,
    id: 'RAW_DATA',
    label: 'RAW DATA',
    description: 'Unprocessed primary sources: raw CDR dumps, CCTV binaries, packet captures, unparsed ledgers.',
    color: '#94a3b8',
    badgeClass: 'epistemic-raw'
  },
  {
    tier: 2,
    id: 'EXTRACTED_ENTITY',
    label: 'EXTRACTED ENTITY',
    description: 'Named entities extracted via NER, regex, or manual extraction: people, phones, accounts, vehicles.',
    color: '#38bdf8',
    badgeClass: 'epistemic-entity'
  },
  {
    tier: 3,
    id: 'OBSERVED_EVENT',
    label: 'OBSERVED EVENT',
    description: 'Physical or digital occurrences anchored in time and space: calls, port clearances, wire transfers.',
    color: '#818cf8',
    badgeClass: 'epistemic-event'
  },
  {
    tier: 4,
    id: 'EVIDENCE',
    label: 'EVIDENCE',
    description: 'Legally admissible artifacts with cryptographic SHA-256 hash and unbroken chain-of-custody.',
    color: '#34d399',
    badgeClass: 'epistemic-evidence'
  },
  {
    tier: 5,
    id: 'VERIFIED_RELATIONSHIP',
    label: 'VERIFIED RELATIONSHIP',
    description: 'Dual-corroborated links between entities supported by independent evidence lines.',
    color: '#a78bfa',
    badgeClass: 'epistemic-relationship'
  },
  {
    tier: 6,
    id: 'ANALYTICAL_INFERENCE',
    label: 'ANALYTICAL INFERENCE',
    description: 'Pattern deductions generated by Byomkesh autonomous sweeps or investigator graph analysis.',
    color: '#fbbf24',
    badgeClass: 'epistemic-inference'
  },
  {
    tier: 7,
    id: 'INVESTIGATIVE_HYPOTHESIS',
    label: 'INVESTIGATIVE HYPOTHESIS',
    description: 'Falsifiable working theories of guilt, syndicate coordination, or motive subject to challenge.',
    color: '#f87171',
    badgeClass: 'epistemic-hypothesis'
  }
];

// ── 16 MASTER CATEGORIES ───────────────────────────────────────────
export const MASTER_CATEGORIES = {
  '01_CASES': {
    code: '01',
    name: 'CASES',
    types: ['Case', 'Sub-case', 'Investigation', 'Complaint', 'FIR / Report', 'Incident', 'Offense', 'Investigation task', 'Lead', 'Hypothesis', 'Alert']
  },
  '02_PEOPLE': {
    code: '02',
    name: 'PEOPLE',
    types: ['Person', 'Victim', 'Witness', 'Informant', 'Suspect', 'Accused', 'Convicted person', 'Missing person', 'Deceased person', 'Investigator', 'Officer', 'Lawyer', 'Other relevant person']
  },
  '03_IDENTITIES': {
    code: '03',
    name: 'IDENTITIES',
    types: ['Legal identity', 'Alias', 'Nickname', 'Username', 'Online identity', 'Passport', 'Government ID', 'License', 'Employee ID', 'Student ID', 'Other identifier']
  },
  '04_COMMUNICATION': {
    code: '04',
    name: 'COMMUNICATION',
    types: ['Phone number', 'SIM', 'Email address', 'Email account', 'Social-media account', 'Messaging account', 'Chat', 'Message', 'Call', 'Voicemail', 'Contact list']
  },
  '05_DEVICES': {
    code: '05',
    name: 'DEVICES',
    types: ['Mobile phone', 'Smartphone', 'Computer', 'Laptop', 'Tablet', 'Server', 'Router', 'IoT device', 'SIM device', 'IMEI', 'MAC address', 'Device identifier', 'Storage media']
  },
  '06_DIGITAL_NETWORK': {
    code: '06',
    name: 'DIGITAL / NETWORK',
    types: ['IP address', 'Domain', 'Website', 'URL', 'Online account', 'Cloud account', 'Digital wallet', 'Cryptocurrency wallet', 'Blockchain address', 'File', 'Digital document', 'Metadata', 'Digital session', 'Login', 'Network connection']
  },
  '07_FINANCIAL': {
    code: '07',
    name: 'FINANCIAL',
    types: ['Bank', 'Bank account', 'Branch', 'Credit/debit card', 'UPI ID', 'Payment account', 'Wallet', 'Cryptocurrency wallet', 'Transaction', 'Transfer', 'Deposit', 'Withdrawal', 'Loan', 'Invoice', 'Payment', 'Financial institution']
  },
  '08_ORGANIZATIONS': {
    code: '08',
    name: 'ORGANIZATIONS',
    types: ['Company', 'Corporation', 'Business', 'Partnership', 'NGO', 'Government organization', 'Agency', 'Institution', 'School', 'College', 'Association', 'Criminal organization', 'Informal group', 'Department', 'Branch / office']
  },
  '09_LOCATIONS': {
    code: '09',
    name: 'LOCATIONS',
    types: ['Country', 'State', 'District', 'City', 'Town', 'Village', 'Neighborhood', 'Street', 'Address', 'Building', 'House', 'Apartment', 'Office', 'Business location', 'Crime scene', 'Meeting location', 'Landmark', 'GPS coordinate', 'Geofence', 'Cell tower', 'Port', 'Airport', 'Border crossing']
  },
  '10_VEHICLES': {
    code: '10',
    name: 'VEHICLES',
    types: ['Car', 'Motorcycle', 'Truck', 'Bus', 'Van', 'Boat', 'Aircraft', 'Train', 'Vehicle registration', 'VIN / chassis number', 'License plate', 'Vehicle owner', 'Vehicle trip']
  },
  '11_ASSETS_OBJECTS': {
    code: '11',
    name: 'ASSETS / OBJECTS',
    types: ['Property', 'Land', 'Building', 'Weapon', 'Tool', 'Document', 'Identification card', 'Bank card', 'Phone', 'Computer', 'Vehicle', 'Package', 'Container', 'Physical evidence', 'Other object']
  },
  '12_EVENTS': {
    code: '12',
    name: 'EVENTS',
    types: ['Crime', 'Incident', 'Meeting', 'Call', 'Message', 'Transaction', 'Login', 'Logout', 'Location visit', 'Vehicle movement', 'Purchase', 'Sale', 'Transfer', 'Travel', 'Arrest', 'Search', 'Seizure', 'Interview', 'Statement', 'Court event', 'Communication event', 'Digital event']
  },
  '13_EVIDENCE': {
    code: '13',
    name: 'EVIDENCE',
    types: ['Document', 'Photograph', 'Video', 'Audio', 'CCTV footage', 'Call record', 'Financial record', 'Chat record', 'Email', 'Location record', 'Device data', 'Forensic report', 'Fingerprint', 'DNA record', 'Physical evidence', 'Digital evidence', 'Witness statement', 'Expert report', 'OSINT source']
  },
  '14_LEGAL': {
    code: '14',
    name: 'LEGAL',
    types: ['Law', 'Section', 'Offense', 'Charge', 'FIR', 'Complaint', 'Arrest', 'Bail', 'Warrant', 'Summons', 'Court case', 'Court order', 'Judgment', 'Conviction', 'Acquittal', 'Sentence', 'Legal proceeding']
  },
  '15_INTELLIGENCE': {
    code: '15',
    name: 'INTELLIGENCE',
    types: ['Lead', 'Tip', 'Observation', 'Intelligence report', 'Intelligence assessment', 'Pattern', 'Anomaly', 'Association', 'Network', 'Threat', 'Risk indicator', 'Hypothesis', 'Investigative finding', 'AI inference']
  },
  '16_RELATIONSHIPS': {
    code: '16',
    name: 'RELATIONSHIPS',
    types: [
      'OWNS', 'USES', 'OWNS_ACCOUNT', 'CONTROLS', 'EMPLOYS', 'WORKS_FOR',
      'KNOWS', 'CONTACTS', 'CALLS', 'MESSAGES', 'EMAILS', 'TRANSFERS_TO',
      'PAID', 'RECEIVED_FROM', 'LOCATED_AT', 'VISITED', 'TRAVELED_TO',
      'TRAVELED_WITH', 'DRIVES', 'REGISTERED_TO', 'LIVES_AT', 'WORKS_AT',
      'MEMBER_OF', 'ASSOCIATED_WITH', 'RELATED_TO_CASE', 'INVOLVED_IN',
      'WITNESSED', 'VICTIM_OF', 'ACCUSED_OF', 'EVIDENCE_OF', 'SUPPORTED_BY',
      'CONTRADICTED_BY', 'DERIVED_FROM'
    ]
  }
};

// ── CRIME GENRES (FOR NETFLIX-STYLE ORGANIZATION) ──────────────────
export const CRIME_GENRES = [
  {
    id: 'narcotics',
    title: 'Narcotics & Drug Trafficking',
    subtitle: 'Cartel distribution, maritime lightering, chemical precursor flows',
    tag: 'NARCOTICS',
    cases: ['case-102']
  },
  {
    id: 'corporate_fraud',
    title: 'Corporate Fraud & Financial Crimes',
    subtitle: 'Hawala conduits, shell company layering, AML wire discrepancies',
    tag: 'FINANCIAL CRIME',
    cases: ['case-117']
  },
  {
    id: 'trafficking',
    title: 'Human Trafficking & Smuggling',
    subtitle: 'Cross-border forced transit, counterfeit passports, safehouse syndicates',
    tag: 'HUMAN TRAFFICKING',
    cases: ['case-143']
  },
  {
    id: 'homicide',
    title: 'Homicide & Contract Murders',
    subtitle: 'Physical assault crimes, forensic DNA matching, ballistics analysis',
    tag: 'HOMICIDE',
    cases: ['case-108']
  },
  {
    id: 'robbery',
    title: 'Armed Robbery & High-Value Heists',
    subtitle: 'Commercial vault breaches, armed incursions, bullion interception',
    tag: 'ROBBERY',
    cases: ['case-121']
  },
  {
    id: 'blackmail',
    title: 'Extortion & Syndicate Blackmail',
    subtitle: 'Digital ransom demands, covert wiretaps, coerced officer signatures',
    tag: 'EXTORTION',
    cases: ['case-135']
  },
  {
    id: 'civil_maritime',
    title: 'Civil Cases & Maritime Sanctions Evasion',
    subtitle: 'Ghost ship transponders, illegal bunkering, flag registry spoofing',
    tag: 'MARITIME',
    cases: ['case-155']
  },
  {
    id: 'cyber',
    title: 'Cyber & Digital Network Infiltration',
    subtitle: 'Encrypted Thuraya bursts, darknet escrow nodes, credential breaches',
    tag: 'CYBERCRIME',
    cases: ['case-168']
  }
];

// ── EXTENSIVE CROSS-CASE REPOSITORY ────────────────────────────────
export const CROSS_CASE_REGISTRY = [
  // Case 102 Entities
  {
    id: 'p-1',
    name: 'Tariq "The Anchor" Merchant',
    category: '02_PEOPLE',
    specificType: 'Suspect',
    caseId: 'case-102',
    caseName: 'Case 102 (Silver Dune)',
    provenance: 'ANALYTICAL_INFERENCE',
    role: 'Syndicate Coordinator',
    threat: 'CRITICAL',
    details: 'Alleged beneficial owner of Al-Barakah FZE. Linked to multiple shell corporations in Surat and Dubai.',
    genre: 'narcotics'
  },
  {
    id: 'p-2',
    name: 'Rajesh Sharma',
    category: '02_PEOPLE',
    specificType: 'Accused',
    caseId: 'case-102',
    caseName: 'Case 102 (Silver Dune)',
    provenance: 'OBSERVED_EVENT',
    role: 'Charter Broker',
    threat: 'HIGH',
    details: 'Surat-based freight broker who cleared cargo papers for MV Sagar Ratna 31 hrs post-docking.',
    genre: 'narcotics'
  },
  {
    id: 'org-1',
    name: 'Al-Barakah Logistics FZE',
    category: '08_ORGANIZATIONS',
    specificType: 'Criminal organization',
    caseId: 'case-102',
    caseName: 'Case 102 (Silver Dune)',
    provenance: 'ANALYTICAL_INFERENCE',
    role: 'Shell Charterer (Dubai)',
    threat: 'CRITICAL',
    details: 'Registered in JAFZA Zone 4. Operating bank mirror accounts used to settle hawala tranches.',
    genre: 'narcotics'
  },
  {
    id: 'veh-1',
    name: 'MV Sagar Ratna (IMO 921882)',
    category: '10_VEHICLES',
    specificType: 'Boat',
    caseId: 'case-102',
    caseName: 'Case 102 (Silver Dune)',
    provenance: 'RAW_DATA',
    role: 'Bulk Cargo Carrier',
    threat: 'HIGH',
    details: 'Panama-flagged bulk carrier. 1.4-meter draft reduction recorded offshore Kandla berth.',
    genre: 'narcotics'
  },
  {
    id: 'fin-1',
    name: 'Hawala Account #88219',
    category: '07_FINANCIAL',
    specificType: 'Payment account',
    caseId: 'case-102',
    caseName: 'Case 102 (Silver Dune)',
    provenance: 'VERIFIED_RELATIONSHIP',
    role: '₹14.8 Cr Settlement Mirror',
    threat: 'CRITICAL',
    details: 'Shared ledger conduit linking Silver Dune split tranches to Dubai bullion trade.',
    genre: 'corporate_fraud'
  },

  // Case 117 Entities (Operation Black Tide)
  {
    id: 'p-101',
    name: 'Farhan "Ghost" Qureshi',
    category: '02_PEOPLE',
    specificType: 'Suspect',
    caseId: 'case-117',
    caseName: 'Case 117 (Operation Black Tide)',
    provenance: 'ANALYTICAL_INFERENCE',
    role: 'AML Smurfing Master',
    threat: 'CRITICAL',
    details: 'Operates 28 straw accounts across Mumbai and Colombo. Direct phone link to Tariq Merchant.',
    genre: 'corporate_fraud'
  },
  {
    id: 'org-102',
    name: 'Blue Horizon Marine Exports LLP',
    category: '08_ORGANIZATIONS',
    specificType: 'Company',
    caseId: 'case-117',
    caseName: 'Case 117 (Operation Black Tide)',
    provenance: 'EXTRACTED_ENTITY',
    role: 'Surat SEZ Front Entity',
    threat: 'HIGH',
    details: 'Incorporated with ₹50 Lakh capital. Signatory seal matches Al-Barakah logistics broker.',
    genre: 'corporate_fraud'
  },
  {
    id: 'evd-103',
    name: 'SWIFT Transfer Log #FIU-99201',
    category: '13_EVIDENCE',
    specificType: 'Financial record',
    caseId: 'case-117',
    caseName: 'Case 117 (Operation Black Tide)',
    provenance: 'EVIDENCE',
    role: 'Cryptographic SWIFT Trace',
    threat: 'HIGH',
    details: '₹4.8 Cr wire from Colombo escrow to Deira Gold Souk bullion merchant.',
    genre: 'corporate_fraud'
  },

  // Case 143 Entities (Red Sand Syndicate)
  {
    id: 'p-201',
    name: 'Dinesh "Koli" Patel',
    category: '02_PEOPLE',
    specificType: 'Suspect',
    caseId: 'case-143',
    caseName: 'Case 143 (Red Sand Syndicate)',
    provenance: 'OBSERVED_EVENT',
    role: 'Coastal Smuggling Dhow Master',
    threat: 'HIGH',
    details: 'Operated unflagged wooden dhows intercepted during nocturnal lightering off Porbandar.',
    genre: 'trafficking'
  },
  {
    id: 'loc-202',
    name: 'Porbandar Coastal Creek Berth 9',
    category: '09_LOCATIONS',
    specificType: 'Crime scene',
    caseId: 'case-143',
    caseName: 'Case 143 (Red Sand Syndicate)',
    provenance: 'RAW_DATA',
    role: 'Clandestine Offload Depot',
    threat: 'HIGH',
    details: 'Tidal creek landing point with zero ICEGATE customs surveillance cameras.',
    genre: 'trafficking'
  },

  // Case 108 Entities (Waterfront Contract Hit)
  {
    id: 'p-301',
    name: 'Vikram "Blade" Jadhav',
    category: '02_PEOPLE',
    specificType: 'Suspect',
    caseId: 'case-108',
    caseName: 'Case 108 (Waterfront Contract Hit)',
    provenance: 'OBSERVED_EVENT',
    role: 'Shooter / Hitman',
    threat: 'CRITICAL',
    details: 'Associated with customs informant assassination at Dock 4. 9mm shell casings recovered.',
    genre: 'homicide'
  },
  {
    id: 'evd-302',
    name: '9mm Glock Ballistics Report',
    category: '13_EVIDENCE',
    specificType: 'Forensic report',
    caseId: 'case-108',
    caseName: 'Case 108 (Waterfront Contract Hit)',
    provenance: 'EVIDENCE',
    role: 'Forensic Ballistics Proof',
    threat: 'CRITICAL',
    details: 'Striation match on breech face certified with HMAC SHA-256 by Central Forensic Lab.',
    genre: 'homicide'
  },

  // Case 121 Entities (Diamond Bourse Vault Breach)
  {
    id: 'p-401',
    name: 'Arjun Singhania (Insider)',
    category: '02_PEOPLE',
    specificType: 'Accused',
    caseId: 'case-121',
    caseName: 'Case 121 (Diamond Bourse Vault Breach)',
    provenance: 'ANALYTICAL_INFERENCE',
    role: 'Security Access Controller',
    threat: 'HIGH',
    details: 'Provided biometric access override codes 12 minutes before vault sensor blackout.',
    genre: 'robbery'
  },
  {
    id: 'evd-402',
    name: 'CCTV Biometric Log #BK-882',
    category: '13_EVIDENCE',
    specificType: 'CCTV footage',
    caseId: 'case-121',
    caseName: 'Case 121 (Diamond Bourse Vault Breach)',
    provenance: 'EVIDENCE',
    role: 'Vault Turnstile Surveillance',
    threat: 'HIGH',
    details: 'Timestamped footage showing override card swipe with masked accomplice.',
    genre: 'robbery'
  },

  // Case 135 Entities (Operation Black Pearl Extortion)
  {
    id: 'p-501',
    name: 'Sameer "Viper" Mir',
    category: '02_PEOPLE',
    specificType: 'Suspect',
    caseId: 'case-135',
    caseName: 'Case 135 (Black Pearl Extortion)',
    provenance: 'OBSERVED_EVENT',
    role: 'Extortion Ring Leader',
    threat: 'HIGH',
    details: 'Voice intercepted demanding ₹2 Crore protection tribute from Kandla port logistics contractors.',
    genre: 'blackmail'
  },

  // Case 155 Entities (Blue Horizon Maritime)
  {
    id: 'veh-601',
    name: 'MT Desert Pearl (Ghost Tanker)',
    category: '10_VEHICLES',
    specificType: 'Boat',
    caseId: 'case-155',
    caseName: 'Case 155 (Blue Horizon Maritime)',
    provenance: 'RAW_DATA',
    role: 'Sanctions Evasion Tanker',
    threat: 'HIGH',
    details: 'Transponder spoofed as fishing trawler while offloading sanctioned crude in deep water.',
    genre: 'civil_maritime'
  },

  // Case 168 Entities (Darknet Cyber Intercepts)
  {
    id: 'dig-701',
    name: 'Thuraya Frequency Band 1544.15 MHz',
    category: '06_DIGITAL_NETWORK',
    specificType: 'Network connection',
    caseId: 'case-168',
    caseName: 'Case 168 (Darknet Cyber Intercepts)',
    provenance: 'OBSERVED_EVENT',
    role: 'Encrypted Radio Burst',
    threat: 'CRITICAL',
    details: 'Diffie-Hellman encrypted packet burst triangulated off Porbandar coastal light beacon.',
    genre: 'cyber'
  }
];
