import './ProvenanceBadge.css';

const PROVENANCE_LEVELS = {
  'RAW DATA': {
    label: 'RAW DATA',
    description: 'Unprocessed primary source document or signal',
    color: 'var(--prov-raw)',
    bg: 'rgba(100, 116, 139, 0.12)',
    border: 'rgba(100, 116, 139, 0.3)'
  },
  'OBSERVATION': {
    label: 'OBSERVATION',
    description: 'Direct factual observation recorded by investigator or sensor',
    color: 'var(--prov-observation)',
    bg: 'var(--accent-blue-subtle)',
    border: 'rgba(59, 130, 246, 0.3)'
  },
  'CORRELATION': {
    label: 'CORRELATION',
    description: 'Statistical or temporal match linking two or more data points',
    color: 'var(--prov-correlation)',
    bg: 'var(--accent-violet-subtle)',
    border: 'rgba(139, 92, 246, 0.3)'
  },
  'INFERENCE': {
    label: 'INFERENCE',
    description: 'Derived deduction generated by analytical graph or entity resolution',
    color: 'var(--prov-inference)',
    bg: 'var(--accent-amber-subtle)',
    border: 'rgba(245, 158, 11, 0.3)'
  },
  'HYPOTHESIS': {
    label: 'HYPOTHESIS',
    description: 'Working theoretical assertion subject to challenge and counter-evidence',
    color: 'var(--prov-hypothesis)',
    bg: 'var(--accent-red-subtle)',
    border: 'var(--accent-red-border)'
  }
};

export default function ProvenanceBadge({ level = 'RAW DATA', size = 'sm' }) {
  const config = PROVENANCE_LEVELS[level.toUpperCase()] || PROVENANCE_LEVELS['RAW DATA'];

  return (
    <span
      className={`provenance-badge prov-${size}`}
      style={{
        color: config.color,
        background: config.bg,
        borderColor: config.border
      }}
      title={`${config.label}: ${config.description}`}
    >
      <span className="prov-dot" style={{ backgroundColor: config.color }} />
      <span className="prov-text">{config.label}</span>
    </span>
  );
}
